### ISSUE TITLE
Exam Cheating Feedback

### ISSUE THREAD

**Issue by wenzhongfa** [jackbergus/NCL_CSC3232#1]
Hello, classmates, I would like to ask for the homework of CSC3232. A student hired a writer outside the school to cheat. Which teacher should I ask for feedback? Please provide your email address or link, I would like to give feedback

**Comment by thebergami** [comment]
Please directly e-mail the module leader with your uni e-mail for this.

**Comment by wenzhongfa** [comment]
yes，it's just that i don't know who the person in charge of the course is, can you tell me, thank you very much

**Comment by thebergami** [comment]
This information is provided here: https://www.ncl.ac.uk/mobility/newcastle/study-abroad/CSC3232
